### ISSUE TITLE
iOS crashes/reloads infinitely when creating a representation for a .cif structure

### ISSUE THREAD

**Issue by luk27official** [molstar/molstar#798]
Hello,
when trying to load some predicted AlphaFold _.cif_ structures into Mol* (i.e **Q5VSL9**), the browser crashes or the page reloads infinitely using Chrome, Firefox and Safari on iOS 16.3+ (tested on multiple devices, neither of the browsers work).

For Android phones and desktop devices, everything works perfectly as expected, but for iPhones XR/SE the page does not load at all.
Unfortunately, although the page does not load properly, there are no logs available.

I load the structure into Mol* in the following way:

```ts
async function loadStructureIntoMolstar(structureUrl: string) {
    const data = await plugin.builders.data.download({
        url: Asset.Url(structureUrl),
        isBinary: false
    }, {state: {isGhost: true}});

    const trajectory = await plugin.builders.structure.parseTrajectory(data, "mmcif");
    const model = await plugin.builders.structure.createModel(trajectory);
    const structure = await plugin.builders.structure.createStructure(model, {name: 'model', params: {}});
    const polymer = await plugin.builders.structure.tryCreateComponentStatic(structure, 'polymer');
    if (!polymer) return;
       
    await plugin.builders.structure.representation.addRepresentation(polymer, {
        type: 'gaussian-surface'
    });
}
```

I suspect the `plugin.builders.structure.representation.addRepresentation` method to contain the problem.

Is there anything I am doing wrong?
Thanks in advance!

**Comment by dsehnal** [comment]
I have tried to load an AF structure on my 16.3+ iPhone 13 with Safari and it works on `https://molstar.org/viewer`.

Maybe there is something about how you are embedding the Mol* viewer which causes this? Perhaps a debug react build with Strict mode on and initializing the plugin in `useEffect`? (the issue is that the `useEffect` is called twice in this scenario).

**Comment by luk27official** [comment]
I have just tried to play around with it once more and noticed that the bug only happens when for `type: 'gaussian-surface'`, for cartoon, it loads properly.

By the way, I have tried changing the type in `https://molstar.org/viewer` for the *Q5VSL9* structure to gaussian surface and the website does not crash, but the structure is all black (on desktops everything works properly again and the residues are colored by pLDDT). Could this be related to my problem? I am attaching a screenshot.

![IMG_4771](https://user-images.githubusercontent.com/1692163/233990508-d75003c6-8329-43a3-afef-7bf8cfecb8be.jpg)

**Comment by dsehnal** [comment]
I was able to reproduce the black structure with the AF structure with `tryUseGpu: true`. Setting `tryUseGpu: false` fixed this.

=> adding `typeParams: { tryUseGpu: false }` should resolve it for you, but the loading will be slower.

Hopefully this will be resolved with Safari 16.4, as this code used to work previously but then they changed something in their WebGL implementation.

Any other ideas @arose?

**Comment by luk27official** [comment]
Thanks, setting `tryUseGpu: false` for creation of gaussian surface representations works for the original problem, it is true that the loading is slightly slower.

Feel free to close the issue, I am leaving it open just for your discussion.

**Comment by MadCatX** [comment]
1) I have been experiencing similar crash-and-reload situations in my own application that uses Molstar. I suspect that the actual problem is Safari's rather strict memory limit on iOS. Some unofficial reports mention the limit is around 400 MiB (https://stackoverflow.com/questions/74506298/how-much-the-memory-limitation-is-on-the-ios-device-browser). With a large enough structure, perhaps the memory just runs out? Debug builds might compound the problem.

2) Has the Viewer been updated to 3.34? There have been some fixes for the black structure bug in 3.34.

**Comment by arose** [comment]
@luk27official do you still see the issue?

**Comment by luk27official** [comment]
Yes, this still happens with v3.40.1, iOS 17.0.2 (both the bugs are still present - my website crashes without `tryUseGpu: false` and the gaussian structure representation on Mol* website is black).

**Comment by arose** [comment]
Hi, I was able to reproduce the issue on browserstack.com, more easily on older iPhones on iOS 17. However I don't get any errors in the console, just page reloads. My guess is the same as @MadCatX that it is a memory issue. Could someone hard-code maxTextureSize to 4096 in https://github.com/molstar/molstar/blob/b53a52b04d3d0e0a5f02a102cfe4cfedb3c8cc66/src/mol-gl/webgl/context.ts#L246 and try on iOS? If that solves it we can add some code to estimate texture size limits differently on iOS (or mobile). Even on an iPhone 11 Pro, the maxTextureSize is reported as 16384 which seems overly high. We use maxTextureSize to decide if e.g. a GaussianSurface can be done on the GPU. So if maxTextureSize is too small for some structure we run the calculation on the CPU (which you force by using tryUseGpu: false).

**Comment by luk27official** [comment]
Hi, yes, the value of 4096 works for me. Some operations on the structure (e.g. overpaints of gaussian surface) take some time, but at least it does not crash the browser anymore, which is fine.

I have done some quick tests regarding with hardcoded values (tested on Safari iPhone XR iOS 17, _Q5VSL9_ AF structure - Gaussian Surface):
2048 - OK
4096 - OK
8192 - OK
10000 - crashes
12000 - crashes
16384 - crashes

I'm not sure whether this value depends on the used structure, though.
